---
baseURL: https://xfyun.github.io
title: AI开源计划
theme: hugo-geekdoc

geekdocOverwriteHTMLBase: true
pygmentsUseClasses: true
pygmentsCodeFences: true
timeout: 180000
pluralizeListTitles: false

defaultContentLanguage: zh-cn

disablePathToLower: true
enableGitInfo: true

enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9

taxonomies:
  tag: tags

outputs:
  home:
    - HTML
  page:
    - HTML
  section:
    - HTML
  taxonomy:
    - HTML
  term:
    - HTML
